## We will solve the classic MNIST Problem with a neural network built using QuarkNet library.

In [ ]:
import numpy as np
from quarknet.nn import NeuralNet
from quarknet.layers import Linear
from quarknet.activations import ReLU
from quarknet.loss import MSE
from quarknet.optim import SGD

In [40]:
# We will use tensorflow just to load the dataset. We will not use tensorflow for anything else
from tensorflow.keras.datasets import mnist

# Load data
(x_train, y_train), (x_test, y_test) = mnist.load_data()


# Normalize to [0, 1]
x_train = x_train.astype(np.float32) / 255.0
x_test = x_test.astype(np.float32) / 255.0

# Flatten from 28x28 → 784
x_train = x_train.reshape(-1, 28 * 28)
x_test = x_test.reshape(-1, 28 * 28)

print("inputs: \n", x_train[:3])
print("targets: \n", y_train[:3])

# One-hot encode labels
num_classes = 10
y_train = np.eye(num_classes)[y_train]
y_test = np.eye(num_classes)[y_test]

print("targets: \n", y_train[:3])

inputs: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
targets: 
 [5 0 4]
targets: 
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
model = NeuralNet(
    [
        Linear(input_size=784, output_size=128),
        ReLU(),
        Linear(input_size=128, output_size=10),
    ]
)

In [60]:
model.train(
    inputs=x_train,
    targets=y_train,
    loss=MSE(),
    optimizer=SGD(0.08),
    epochs=50,
    shuffle=True,
)

Epoch No: 0, Loss: 57.02936787711152
Epoch No: 1, Loss: 56.75452885570093
Epoch No: 2, Loss: 56.59461238755182
Epoch No: 3, Loss: 56.431879149262336
Epoch No: 4, Loss: 56.2833652206788
Epoch No: 5, Loss: 56.067437024057455
Epoch No: 6, Loss: 55.99659634636352
Epoch No: 7, Loss: 55.887461640008176
Epoch No: 8, Loss: 55.66618743494662
Epoch No: 9, Loss: 55.654762457811586
Epoch No: 10, Loss: 55.475933931513964
Epoch No: 11, Loss: 55.283220313011526
Epoch No: 12, Loss: 55.29112935418204
Epoch No: 13, Loss: 55.14657357991232
Epoch No: 14, Loss: 55.039707028359175
Epoch No: 15, Loss: 54.953191219341704
Epoch No: 16, Loss: 54.77499589415145
Epoch No: 17, Loss: 54.7007452546502
Epoch No: 18, Loss: 54.6513819017369
Epoch No: 19, Loss: 54.48472951790776
Epoch No: 20, Loss: 54.43589531298935
Epoch No: 21, Loss: 54.27809549729413
Epoch No: 22, Loss: 54.13687139492398
Epoch No: 23, Loss: 54.12769310085477
Epoch No: 24, Loss: 53.99322972777935
Epoch No: 25, Loss: 53.9018566185758
Epoch No: 26, Loss

In [61]:
correct = 0

for x, y in zip(x_test, y_test):
    predicted = model.predict(x)
    predicted_index = np.argmax(predicted)
    actual_index = np.argmax(y)
    if predicted_index == actual_index:
        correct += 1

print(f"Accuracy: {(correct / len(x_test)) * 100}%")

Accuracy: 87.62%


## We were able to achieve an accuracy of ~87% on the Classical MNIST problem with a simple neural network we've built using the QuarkNet library.