## FizzBuzz

For each of the numbers 1 to 100:
* If the number is divisible by 3, print "fizz"
* If the number is divisible by 5, print "buzz"
* If the number is divisible by 15, print "fizzbuzz"
* Otherwise just print the number

#### We will use a Neural Network to solve this problem.

In [67]:
import numpy as np
from quarknet.nn import NeuralNet
from quarknet.layers import Linear
from quarknet.activations import Tanh, ReLU, Sigmoid
from quarknet.loss import MSE
from quarknet.optim import SGD

In [76]:
def fizz_buzz_encode(x: int) -> list[int]:
    if x%15 == 0:
        return [0, 0, 0, 1]
    elif x%5 == 0:
        return [0, 0, 1, 0]
    elif x%3 == 0:
        return [0, 1, 0, 0]
    else:
        return [1, 0, 0, 0]


def binary_encode(x: int) -> list[int]:
    """
    10 Digit Binary Encoding of an Integer
    """
    return [((x >> i) & 1) for i in range(10)]  # x // (2^i)

### Let's train our model on numbers range (101 to 1000) and test on the range (1, 100)

In [77]:
# We will use binary encoded arrays of the numbers for training
inputs = np.array([
    binary_encode(x)
    for x in range(101, 1024)
])
print("inputs: \n", inputs)


targets = np.array([
    fizz_buzz_encode(x)
    for x in range(101, 1024)
])
print("targets: \n", targets)

inputs: 
 [[1 0 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 0 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
targets: 
 [[1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 ...
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]


In [78]:
model = NeuralNet([
    Linear(input_size=10, output_size=54),
    Tanh(),
    Linear(input_size=54, output_size=4),
])

In [79]:
model.train(
    inputs=inputs,
    targets=targets,
    loss=MSE(),
    optimizer=SGD(lr=0.04),
    epochs=5000,
)

Epoch No: 0, Loss: 268.3773558511784
Epoch No: 1, Loss: 82.31899245245229
Epoch No: 2, Loss: 60.697276060940936
Epoch No: 3, Loss: 48.829298625680266
Epoch No: 4, Loss: 40.29148700340216
Epoch No: 5, Loss: 35.13175418206484
Epoch No: 6, Loss: 30.67240069134623
Epoch No: 7, Loss: 27.106714822510284
Epoch No: 8, Loss: 24.21959157718623
Epoch No: 9, Loss: 22.01330309962562
Epoch No: 10, Loss: 20.143176938412417
Epoch No: 11, Loss: 18.6778108978598
Epoch No: 12, Loss: 17.555322014136085
Epoch No: 13, Loss: 16.403404210611765
Epoch No: 14, Loss: 15.191184756309102
Epoch No: 15, Loss: 14.60395156536961
Epoch No: 16, Loss: 13.927962124879537
Epoch No: 17, Loss: 13.395034895354392
Epoch No: 18, Loss: 12.56065049791565
Epoch No: 19, Loss: 12.214795064402733
Epoch No: 20, Loss: 11.790713071818454
Epoch No: 21, Loss: 11.472042912776397
Epoch No: 22, Loss: 11.01476346798766
Epoch No: 23, Loss: 10.728061300849108
Epoch No: 24, Loss: 10.355781345613192
Epoch No: 25, Loss: 10.095326383726416
Epoch No

## Now we'll use the model we've trained to predict the classes on numbers in the range of (0, 100)

In [80]:
correct = 0

for x in range(1, 101):
    predicted = model.predict(binary_encode(x))
    predicted_index = np.argmax(predicted)
    actual_index = np.argmax(fizz_buzz_encode(x))

    if predicted_index == actual_index:
        correct += 1

    # Output classes
    labels = [str(x), "fizz", "buzz", "fizzbuzz"]
    print("Number: ", x, "Predicted: ", labels[predicted_index], "Actual: ", labels[actual_index])


print(f"Accuracy: {correct}%")

Number:  1 Predicted:  1 Actual:  1
Number:  2 Predicted:  2 Actual:  2
Number:  3 Predicted:  fizz Actual:  fizz
Number:  4 Predicted:  4 Actual:  4
Number:  5 Predicted:  buzz Actual:  buzz
Number:  6 Predicted:  fizz Actual:  fizz
Number:  7 Predicted:  7 Actual:  7
Number:  8 Predicted:  8 Actual:  8
Number:  9 Predicted:  fizz Actual:  fizz
Number:  10 Predicted:  buzz Actual:  buzz
Number:  11 Predicted:  11 Actual:  11
Number:  12 Predicted:  fizz Actual:  fizz
Number:  13 Predicted:  13 Actual:  13
Number:  14 Predicted:  14 Actual:  14
Number:  15 Predicted:  fizzbuzz Actual:  fizzbuzz
Number:  16 Predicted:  16 Actual:  16
Number:  17 Predicted:  17 Actual:  17
Number:  18 Predicted:  fizz Actual:  fizz
Number:  19 Predicted:  19 Actual:  19
Number:  20 Predicted:  buzz Actual:  buzz
Number:  21 Predicted:  fizz Actual:  fizz
Number:  22 Predicted:  22 Actual:  22
Number:  23 Predicted:  23 Actual:  23
Number:  24 Predicted:  fizz Actual:  fizz
Number:  25 Predicted:  buzz Ac

In [81]:
X_test = np.array([
    binary_encode(x)
    for x in range(1, 100)
])

targets = np.array([
    fizz_buzz_encode(x)
    for x in range(1, 100)
])

model.test(
    inputs =X_test,
    targets=targets,
    loss = MSE(),
)

Total Loss: 0.1985397511781345


## We were able to achieve an accuracy of ~99% on the Fizz-Buzz problem using a simple neural network we'be built using the QuarkNet library.